
package alquiler_abc.views;

import alquiler_abc_main.Main;
import alquiler_abc.models.Vehicule;
import javax.swing.JOptionPane;

public class AddVehicule extends javax.swing.JFrame {

    /**
     * Creates new form AddVehicule
     */
    public AddVehicule() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox<>();
        mark = new javax.swing.JTextField();
        line = new javax.swing.JTextField();
        plate = new javax.swing.JTextField();
        handleAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(510, 460));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Marca:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 45, 50, 18);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Linea:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 50, 43, 18);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Placa:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 180, 60, 18);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Estado:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 180, 60, 18);

        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Alquilado" }));
        jPanel1.add(state);
        state.setBounds(300, 200, 120, 24);
        jPanel1.add(mark);
        mark.setBounds(20, 70, 170, 24);
        jPanel1.add(line);
        line.setBounds(300, 70, 180, 24);
        jPanel1.add(plate);
        plate.setBounds(20, 200, 120, 24);

        handleAdd.setText("Agregar");
        handleAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        handleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleAddActionPerformed(evt);
            }
        });
        jPanel1.add(handleAdd);
        handleAdd.setBounds(200, 300, 100, 50);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Ir al Menu Principal");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenu(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 360, 150, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleAddActionPerformed
        
        try{
            String plateClient = this.plate.getText();
            validateFieldsEmpty();
            if(!existPlate(plateClient)){
                Main.vehicules.add(new Vehicule(
                    mark.getText(),
                    line.getText(),
                    plateClient,
                    state.getSelectedItem().toString()
                ));
                JOptionPane.showMessageDialog(null, "Se ha agregado correctamente el automovil", "Exitoso", JOptionPane.INFORMATION_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(null,"Error: placa: " + plateClient + ", Ya se encuentra registrada.", "Error en placa", JOptionPane.ERROR_MESSAGE);
        }catch(IllegalArgumentException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_handleAddActionPerformed

    private void openMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenu
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_openMenu
    
    private boolean existPlate(String plate){
        for(Vehicule vehicule : Main.vehicules){
            if(vehicule.getPlate().equals(plate))
                return true;
        }
        return false;
    }
    
    private void validateFieldsEmpty() throws IllegalArgumentException{
        if(plate.getText().isEmpty() || plate.getText().isEmpty())
            throw new IllegalArgumentException("Error en Placa, por favor ingrese un valor.");
        if(mark.getText().isEmpty() || mark.getText().isEmpty())
            throw new IllegalArgumentException("Error en Marca, por favor ingrese un valor.");
        if(line.getText().isEmpty() || line.getText().isEmpty())
            throw new IllegalArgumentException("Error en Linea, por favor ingrese un valor.");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton handleAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField line;
    private javax.swing.JTextField mark;
    private javax.swing.JTextField plate;
    private javax.swing.JComboBox<String> state;
    // End of variables declaration//GEN-END:variables
}
