package alquiler_abc.views;

import alquiler_abc.models.Vehicule;
import alquiler_abc_main.Main;
import javax.swing.table.DefaultTableModel;


public class FindVehicules extends javax.swing.JFrame {

    /**
     * Creates new form FindVehicules
     */
    public FindVehicules() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVehicules = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 460));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                initializeTable(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        tableVehicules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Placa", "Linea", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableVehicules);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 510, 210);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Automoviles");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 60);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Ir al Menu Principal");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenu(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 360, 150, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializeTable(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_initializeTable
        DefaultTableModel model = (DefaultTableModel) tableVehicules.getModel();
        tableVehicules.removeAll();
        for(Vehicule vehicule : Main.vehicules){
            model.addRow(new Object[]{vehicule.getMark(), vehicule.getPlate(), vehicule.getLine(), vehicule.getState()});
        }
    }//GEN-LAST:event_initializeTable

    private void openMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenu
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_openMenu

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVehicules;
    // End of variables declaration//GEN-END:variables
}
