
package alquiler_abc.views;

import alquiler_abc.models.Rent;
import alquiler_abc_main.Main;
import javax.swing.table.DefaultTableModel;

public class FindRent extends javax.swing.JFrame {

    /**
     * Creates new form FindRent
     */
    public FindRent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        identification = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        find = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRents = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(510, 460));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(510, 460));
        jPanel1.setLayout(null);

        identification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificationActionPerformed(evt);
            }
        });
        identification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                find(evt);
            }
        });
        jPanel1.add(identification);
        identification.setBounds(70, 40, 290, 30);

        jLabel1.setText("Numero de Identificacion del Cliente:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 290, 20);

        find.setText("Buscar");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        jPanel1.add(find);
        find.setBounds(380, 40, 100, 30);

        tableRents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Fecha de Alquiler", "Dias de Alquiler"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRents);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 510, 220);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Ir al Menu Principal");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenu(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 380, 150, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, -3, 510, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificationActionPerformed

    private void openMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenu
        dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_openMenu

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        handleFind();
    }//GEN-LAST:event_findActionPerformed

    private void find(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_find
        if(evt.getKeyCode() == 10)
            handleFind();
    }//GEN-LAST:event_find
    
    private void handleFind(){
        DefaultTableModel model = (DefaultTableModel) tableRents.getModel();
        model.setNumRows(0);
        for(Rent rent : Main.rents){
            if(rent.getIdentification().equals(identification.getText()))
                model.addRow(new Object[]{rent.getPlate(), rent.getRentDate(), rent.getRentalDays()});
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton find;
    private javax.swing.JTextField identification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRents;
    // End of variables declaration//GEN-END:variables
}
