
package alquiler_abc.views;

import javax.swing.JOptionPane;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        option = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        handleAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(510, 460));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(510, 460));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 40);

        option.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        option.setToolTipText("Ingrese el numero de la opcion Seleccionada");
        option.setName("option"); // NOI18N
        option.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                send(evt);
            }
        });
        jPanel1.add(option);
        option.setBounds(190, 320, 110, 30);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("5) Consultar Clientes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 320, 18);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("1) Ingreso de automóviles");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 320, 18);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("2) Ingreso de clientes");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 80, 320, 18);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("3) Registro de Alquiler");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 110, 320, 18);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setText("8) Salir");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 260, 320, 18);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setText("4) Consultar Automoviles");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 140, 320, 18);

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setText("6) Consultar Alquileres");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 200, 320, 18);

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setText("7) Consultar Alquileres por cliente");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 230, 320, 18);

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel12.setText("Ingrese el numero de la opcion seleccionada");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 290, 340, 18);

        handleAccept.setText("Aceptar");
        handleAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        handleAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleAcceptActionPerformed(evt);
            }
        });
        jPanel1.add(handleAccept);
        handleAccept.setBounds(200, 380, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleAcceptActionPerformed
        handleAccept();
        
    }//GEN-LAST:event_handleAcceptActionPerformed

    private void handleAccept(){
        try{
            int optionClient = Integer.parseInt(option.getText());
            switch(optionClient){
                case 1 -> {
                    this.dispose();
                    new AddVehicule().setVisible(true);
                }
                case 2 -> {
                    this.dispose();
                    new AddClient().setVisible(true);
                }
                case 3 -> {
                    this.dispose();
                    new RegisterRent().setVisible(true);
                }
                case 4 -> {
                    this.dispose();
                    new FindVehicules().setVisible(true);
                }
                case 5 -> {
                    this.dispose();
                    new FindClients().setVisible(true);
                }
                case 6 -> {
                    this.dispose();
                    new FindRents().setVisible(true);
                }
                case 7 -> {
                    this.dispose();
                    new FindRent().setVisible(true);
                }
                case 8 -> System.exit(0);
                default -> throw new IllegalArgumentException("Opcion "+ option + " No valida");
            }
                
            
        }catch(NumberFormatException | NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Opcion no valida");
        }
        catch(IllegalArgumentException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void send(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_send
        if(evt.getKeyCode() == 10)
            handleAccept();
        
    }//GEN-LAST:event_send

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton handleAccept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField option;
    // End of variables declaration//GEN-END:variables
}
